" general
source    $HOME/.config/nvim/general/autocmd.vim
source    $HOME/.config/nvim/general/spellcheck.vim
source    $HOME/.config/nvim/general/sets.vim
source    $HOME/.config/nvim/general/plugins.vim

" plugins
source    $HOME/.config/nvim/plug-config/vim-coc.vim
source    $HOME/.config/nvim/plug-config/vim-highlightedyank.vim
source    $HOME/.config/nvim/plug-config/vim-taboo.vim
source    $HOME/.config/nvim/plug-config/vim-colorizer.vim
source    $HOME/.config/nvim/plug-config/vim-pencil.vim
source    $HOME/.config/nvim/plug-config/vim-startify.vim
source    $HOME/.config/nvim/plug-config/vim-neoscroll.vim
source    $HOME/.config/nvim/plug-config/vim-markdown-preview.vim
source    $HOME/.config/nvim/plug-config/vim-gitignore.vim
source    $HOME/.config/nvim/plug-config/vim-lazygit.vim
source    $HOME/.config/nvim/plug-config/vim-nvimtree.vim
source    $HOME/.config/nvim/plug-config/peekup.vim
luafile   $HOME/.config/nvim/plug-config/vim-treesitter.lua
luafile   $HOME/.config/nvim/plug-config/vim-telescope.lua
luafile   $HOME/.config/nvim/plug-config/vim-galaxyline.lua
luafile   $HOME/.config/nvim/plug-config/ftterm.lua

" maps
source    $HOME/.config/nvim/general/theme.vim
source    $HOME/.config/nvim/general/maps/div.vim
source    $HOME/.config/nvim/general/maps/quickfix.vim
source    $HOME/.config/nvim/general/maps/coc.vim
source    $HOME/.config/nvim/general/maps/git.vim
source    $HOME/.config/nvim/general/maps/telescope.vim
source    $HOME/.config/nvim/general/maps/nav.vim
