require("user.options")
require("user.functions")
require("user.plugins")
require("user.configs")
require("user.autocommands")
require("user.colorscheme")
require("user.lsp")
require("user.keybindings")
