" general
source $HOME/.config/nvim/general/autocmd.vim
source $HOME/.config/nvim/general/spellcheck.vim
source $HOME/.config/nvim/general/sets.vim
source $HOME/.config/nvim/general/plugins.vim

" plugins
source $HOME/.config/nvim/plugins/vim-fzf.vim
source $HOME/.config/nvim/plugins/vim-gitgutter.vim
source $HOME/.config/nvim/plugins/vim-coc.vim
source $HOME/.config/nvim/plugins/vim-nerdtree.vim
source $HOME/.config/nvim/plugins/vim-highlightedyank.vim
source $HOME/.config/nvim/plugins/vim-devicons.vim
source $HOME/.config/nvim/plugins/vim-goyo.vim
source $HOME/.config/nvim/plugins/vim-airline.vim
source $HOME/.config/nvim/plugins/vim-taboo.vim
source $HOME/.config/nvim/plugins/vim-colorizer.vim
source $HOME/.config/nvim/plugins/vim-pencil.vim
source $HOME/.config/nvim/plugins/vim-treesitter.vim
source $HOME/.config/nvim/plugins/vim-startify.vim
source $HOME/.config/nvim/plugins/vim-neoscroll.vim
source $HOME/.config/nvim/plugins/vim-markdown-preview.vim
source $HOME/.config/nvim/plugins/vim-gitignore.vim
source $HOME/.config/nvim/plugins/vim-telescope.vim
source $HOME/.config/nvim/plugins/vim-lazygit.vim

" maps
source $HOME/.config/nvim/general/theme.vim
source $HOME/.config/nvim/general/maps/div.vim
source $HOME/.config/nvim/general/maps/quickfix.vim
source $HOME/.config/nvim/general/maps/coc.vim
source $HOME/.config/nvim/general/maps/git.vim
source $HOME/.config/nvim/general/maps/telescope.vim
source $HOME/.config/nvim/general/maps/nav.vim
