vim.g.transparent_background = false -- transparent background(Default: false)
vim.g.italic_comments = true -- italic comments(Default: true)
vim.g.italic_keywords = true -- italic keywords(Default: true)
vim.g.italic_functions = false -- italic functions(Default: false)
vim.g.italic_variables = false -- italic variables(Default: false)
