-- require("user.configs.cmp")
require("user.configs.telescope")
require("user.configs.fzf-lua")
require("user.configs.treesitter")
require("user.configs.autopairs")
require("user.configs.harpoon")
require("user.configs.comment")
require("user.configs.gitsigns")
require("user.configs.nvim-tree")
require("user.configs.bufferline")
require("user.configs.octo")
require("user.configs.lualine")
require("user.configs.project")
require("user.configs.diffview")
require("user.configs.impatient")
require("user.configs.indentline")
require("user.configs.alpha")
