vim.g.nvim_tree_width = 50 
vim.g.nvim_tree_ignore = { '.git', 'node_modules', '.cache' }
vim.g.nvim_tree_gitignore = 0 
vim.g.nvim_tree_auto_open = 1 
vim.g.nvim_tree_auto_close = 0 
vim.g.nvim_tree_auto_ignore_ft = { 'startify', 'dashboard' } 
vim.g.nvim_tree_quit_on_open = 0 
vim.g.nvim_tree_follow = 1 
vim.g.nvim_tree_indent_markers = 0 
vim.g.nvim_tree_hide_dotfiles = 0 
vim.g.nvim_tree_git_hl = 0 
vim.g.nvim_tree_root_folder_modifier = ':~' 
vim.g.nvim_tree_tab_open = 0 
vim.g.nvim_tree_width_allow_resize  = 0 
vim.g.nvim_tree_disable_netrw = 1 
vim.g.nvim_tree_hijack_netrw = 1 
vim.g.nvim_tree_add_trailing = 0 
vim.g.nvim_tree_group_empty = 0 
vim.g.nvim_tree_lsp_diagnostics = 0 
vim.g.nvim_tree_special_files = { 'README.md', 'Makefile', 'MAKEFILE' }
